//
// Created by aagui on 02-05-2026.
//

#ifndef BENJAMINROJAS_BRANDONNAVEA_TALLER1_MEDIAPLAYER_HPP
#define BENJAMINROJAS_BRANDONNAVEA_TALLER1_MEDIAPLAYER_HPP



class MediaPlayer {

};



#endif //BENJAMINROJAS_BRANDONNAVEA_TALLER1_MEDIAPLAYER_HPP
